sudo: false

branches:
    except:
        - releases

language: perl

perl:
    - "5.26"
    - "5.24"
    - "5.22"

install:
    - dzil authordeps --missing | cpanm || { cat ~/.cpanm/build.log ; false ; }
    - dzil listdeps --author --missing | cpanm || { cat ~/.cpanm/build.log ; false ; }

script:
    - dzil test --author --release
