---
abstract: 'Encrypted cookie-based session backend for Dancer'
author:
  - 'Alex Kapranoff <kappa@cpan.org>'
  - 'Alex Sukria <sukria@cpan.org>'
  - 'David Golden <dagolden@cpan.org>'
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  Dancer::ModuleLoader: '0'
  Dancer::Test: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
  FindBin: '0'
  HTTP::Cookies: '0'
  HTTP::Date: '0'
  HTTP::Request::Common: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Plack: '1.0029'
  Plack::Test: '0'
  Test::Exception: '0'
  Test::More: '0.96'
  Test::NoWarnings: '0'
  Test::Requires: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.011, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer-Session-Cookie
provides:
  Dancer::Session::Cookie:
    file: lib/Dancer/Session/Cookie.pm
    version: '0.30'
requires:
  Crypt::CBC: '0'
  Crypt::Rijndael: '0'
  Dancer: '1.3113'
  Dancer::Cookie: '0'
  Dancer::Cookies: '0'
  Dancer::Session::Abstract: '0'
  MIME::Base64: '0'
  PerlX::Maybe: '0'
  Session::Storage::Secure: '0.010'
  Storable: '0'
  String::CRC32: '0'
  Time::Duration::Parse: '0'
  parent: '0'
  perl: v5.10.0
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/perldancer/Dancer-Session-Cookie/issues
  homepage: https://github.com/perldancer/Dancer-Session-Cookie
  repository: https://github.com/perldancer/Dancer-Session-Cookie.git
version: '0.30'
x_authority: cpan:YANICK
x_contributors:
  - 'Breno G. de Oliveira <garu@cpan.org>'
  - 'David Precious <davidp@preshweb.co.uk>'
  - 'Michael G. Schwern <schwern@pobox.com>'
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
  - 'Neil Kirsopp <neil@broadbean.com>'
  - 'Nick S. Knutov <nick@knutov.com>'
  - 'Paul Cochrane <paul@liekut.de>'
  - 'Sawyer X <xsawyerx@cpan.org>'
x_serialization_backend: 'YAML::Tiny version 1.67'
